/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : Cashflow.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.myfinance.api.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cashflow generated by hbm2java
*/
@Entity
@Table(
    name="mf_cashflow")
@ApiModel
public class Cashflow  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private Integer cashflowid;
     private Integer instrumentId;
     private Integer transactionId;
     private double value;

    public Cashflow() {
    }

    public Cashflow(Integer instrumentId, double value) {
       this.instrumentId = instrumentId;
       this.value = value;
    }

    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="cashflowid", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public Integer getCashflowid() {
        return this.cashflowid;
    }
    public void setCashflowid(Integer cashflowid) {
        this.cashflowid = cashflowid;
    }

    @Column(name = "instrumentid", nullable=false)
    @ApiModelProperty(required = true)
    protected Integer getInstrumentId() {
        return this.instrumentId;
    }
    protected void setInstrumentId(Integer instrumentId) {
        this.instrumentId = instrumentId;
    }

    @Column(name = "transactionid", nullable=false)
    @ApiModelProperty(required = true)
    protected Integer getTransactionId() {
        return this.transactionId;
    }
    protected void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

    @Column(name="value", nullable=false, precision=10)
    @ApiModelProperty(required = true)
    public double getValue() {
        return this.value;
    }
    public void setValue(double value) {
        this.value = value;
    }




}
