/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : Cashflow.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.myfinance.api.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Cashflow generated by hbm2java
*/
@Entity
@Table(
    name="mf_cashflow")
@ApiModel
public class Cashflow  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private Integer cashflowid;
     private Instrument instrument;
     private Transaction transaction;
     private double value;

    public Cashflow() {
    }

    public Cashflow(Instrument instrument, double value) {
       this.instrument = instrument;
       this.value = value;
    }

    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="cashflowid", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public Integer getCashflowid() {
        return this.cashflowid;
    }
    public void setCashflowid(Integer cashflowid) {
        this.cashflowid = cashflowid;
    }



    @ManyToOne( fetch = FetchType.EAGER )
    @JoinColumn(name = "instrumentid", nullable = false )
    @ApiModelProperty(required = true)
    public Instrument getInstrument() {
        return this.instrument;
    }
    public void setInstrument(Instrument instrument) {
        this.instrument = instrument;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn(name = "transactionid", nullable = false )
    @JsonBackReference
    @ApiModelProperty(required = true)
    public Transaction getTransaction() {
        return this.transaction;
    }
    public void setTransaction(Transaction transaction) {
        this.transaction = transaction;
    }

    @Column(name="value", nullable=false, precision=10)
    @ApiModelProperty(required = true)
    public double getValue() {
        return this.value;
    }
    public void setValue(double value) {
        this.value = value;
    }




}
