/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : EndOfDayPrice.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.myfinance.api.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * EndOfDayPrice generated by hbm2java
*/
@Entity
@Table(
    name="mf_endofdayprice")
@ApiModel
public class EndOfDayPrice  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private int endofdaypriceid;
     private Instrument currency;
     private Instrument security;
     private Source source;
     private LocalDate dayofprice;
     private Double value;
     private LocalDateTime lastchanged;

    public EndOfDayPrice() {
    }

	
    public EndOfDayPrice(int endofdaypriceid) {
        this.endofdaypriceid = endofdaypriceid;
    }
    public EndOfDayPrice(Instrument currency, Instrument security, Source source, LocalDate dayofprice, Double value, LocalDateTime lastchanged) {
       this.currency = currency;
       this.security = security;
       this.source = source;
       this.dayofprice = dayofprice;
       this.value = value;
       this.lastchanged = lastchanged;
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="endofdaypriceid", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public int getEndofdaypriceid() {
        return this.endofdaypriceid;
    }
    public void setEndofdaypriceid(int endofdaypriceid) {
        this.endofdaypriceid = endofdaypriceid;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="currencyid")
    @ApiModelProperty(required = true)
    public Instrument getCurrency() {
        return this.currency;
    }
    public void setCurrency(Instrument currency) {
        this.currency = currency;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="instrumentid")
    @ApiModelProperty(required = true)
    public Instrument getSecurity() {
        return this.security;
    }
    public void setSecurity(Instrument security) {
        this.security = security;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sourceid")
    @ApiModelProperty(required = true)
    public Source getSource() {
        return this.source;
    }
    public void setSource(Source source) {
        this.source = source;
    }
    
    @Column(name="dayofprice", length=13)
    @ApiModelProperty(required = true)
    public LocalDate getDayofprice() {
        return this.dayofprice;
    }
    public void setDayofprice(LocalDate dayofprice) {
        this.dayofprice = dayofprice;
    }
    
    @Column(name="value", precision=10)
    @ApiModelProperty(required = true)
    public Double getValue() {
        return this.value;
    }
    public void setValue(Double value) {
        this.value = value;
    }
    
    @Column(name="lastchanged", length=19)
    @ApiModelProperty(required = true)
    public LocalDateTime getLastchanged() {
        return this.lastchanged;
    }
    public void setLastchanged(LocalDateTime lastchanged) {
        this.lastchanged = lastchanged;
    }




}
