/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : InstrumentGraphEntry.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.myfinance.api.domain;
// Generated by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InstrumentGraphEntry generated by hbm2java
*/
@Entity
@Table(
    name="mf_instrumentgraph")
public class InstrumentGraphEntry implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private InstrumentGraphId id;
     private int pathlength;

    public InstrumentGraphEntry() {
    }

    public InstrumentGraphEntry(int ancestorId, int descendantId, EdgeType edgeType) {
       this.id = new InstrumentGraphId(ancestorId, descendantId, edgeType);
       this.pathlength = pathlength;
    }

    @EmbeddedId    
    @AttributeOverrides( {
        @AttributeOverride(name="ancestor", column=@Column(name="ancestor", nullable=false) ), 
        @AttributeOverride(name="descendant", column=@Column(name="descendant", nullable=false) ), 
        @AttributeOverride(name="edgetype", column=@Column(name="edgetype", nullable=false) ) } )
    public InstrumentGraphId getId() {
        return this.id;
    }
    public void setId(InstrumentGraphId id) {
        this.id = id;
    }
    

    @Column(name="pathlength", nullable=false)
    public int getPathlength() {
        return this.pathlength;
    }
    public void setPathlength(int pathlength) {
        this.pathlength = pathlength;
    }




}
