/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : InstrumentProperties.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.myfinance.api.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InstrumentProperties generated by hbm2java
*/
@Entity
@Table(
    name="mf_instrumentproperties")
@ApiModel
public class InstrumentProperties  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private Integer propertyid;
     private String propertyname;
     private int instrumentid;
     private String value;
     private String valuetype;
     private LocalDate validfrom;
     private LocalDate validto;

    public InstrumentProperties() {
    }

	
    public InstrumentProperties(String propertyname, int instrumentid, String value, String valuetype) {
        this.propertyname = propertyname;
        this.instrumentid = instrumentid;
        this.value = value;
        this.valuetype = valuetype;
    }
    public InstrumentProperties(String propertyname, int instrumentid, String value, String valuetype, LocalDate validfrom, LocalDate validto) {
       this.propertyname = propertyname;
       this.instrumentid = instrumentid;
       this.value = value;
       this.valuetype = valuetype;
       this.validfrom = validfrom;
       this.validto = validto;
    }

    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="propertyid", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public Integer getPropertyid() {
        return this.propertyid;
    }
    
    public void setPropertyid(Integer propertyid) {
        this.propertyid = propertyid;
    }
    
    @Column(name="propertyname", nullable=false, length=64)
    @ApiModelProperty(required = true)
    public String getPropertyname() {
        return this.propertyname;
    }
    
    public void setPropertyname(String propertyname) {
        this.propertyname = propertyname;
    }
    
    @Column(name="instrumentid", nullable=false)
    @ApiModelProperty(required = true)
    public int getInstrumentid() {
        return this.instrumentid;
    }
    
    public void setInstrumentid(int instrumentid) {
        this.instrumentid = instrumentid;
    }
    
    @Column(name="value", nullable=false, length=64)
    @ApiModelProperty(required = true)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    @Column(name="valuetype", nullable=false, length=32)
    @ApiModelProperty(required = true)
    public String getValuetype() {
        return this.valuetype;
    }
    
    public void setValuetype(String valuetype) {
        this.valuetype = valuetype;
    }
    
    @Column(name="validfrom", length=13)
    @ApiModelProperty(required = true)
    public LocalDate getValidfrom() {
        return this.validfrom;
    }
    
    public void setValidfrom(LocalDate validfrom) {
        this.validfrom = validfrom;
    }
    
    @Column(name="validto", length=13)
    @ApiModelProperty(required = true)
    public LocalDate getValidto() {
        return this.validto;
    }
    
    public void setValidto(LocalDate validto) {
        this.validto = validto;
    }




}
