/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : Product.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.myfinance.api.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Product generated by hbm2java
*/
@Entity
@Table(
    name="md_product")
@ApiModel
public class Product  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private Integer id;
     private Integer version;
     private String description;
     private String imageUrl;
     private Double price;
     private String productId;

    public Product() {
    }

	
    public Product(String description, String productId) {
        this.description = description;
        this.productId = productId;
    }
    public Product(String description, String imageUrl, Double price, String productId) {
       this.description = description;
       this.imageUrl = imageUrl;
       this.price = price;
       this.productId = productId;
    }

    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="id", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Version
    @Column(name="version")
    @ApiModelProperty(required = true)
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    @Column(name="description", nullable=false)
    @ApiModelProperty(required = true)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="image_url")
    @ApiModelProperty(required = true)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    
    @Column(name="price")
    @ApiModelProperty(required = true)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    
    @Column(name="product_id", nullable=false)
    @ApiModelProperty(required = true)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }




}
