/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : SecuritySymbols.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.myfinance.api.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SecuritySymbols generated by hbm2java
*/
@Entity
@Table(
    name="mf_securitysymbols")
@ApiModel
public class SecuritySymbols  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


    private Integer symbolid;
    private Integer instrumentId;
    private String symbol;
    private Instrument currency;

    public SecuritySymbols() {
    }

    public SecuritySymbols(Instrument currency, Integer instrumentId, String symbol) {
       this.currency = currency;
       this.instrumentId = instrumentId;
       this.symbol = symbol;
    }

    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="symbolid", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public Integer getSymbolid() {
        return this.symbolid;
    }
    public void setSymbolid(Integer symbolid) {
        this.symbolid = symbolid;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="currencyid")
    @ApiModelProperty(required = true)
    public Instrument getCurrency() {
        return this.currency;
    }
    public void setCurrency(Instrument currency) {
        this.currency = currency;
    }

    @Column(name = "instrumentId", nullable=false)
    @ApiModelProperty(required = true)
    protected Integer getInstrumentId() {
        return this.instrumentId;
    }
    protected void setInstrumentId(Integer instrumentId) {
        this.instrumentId = instrumentId;
    }
    
    @Column(name="symbol", nullable=false, length=20)
    @ApiModelProperty(required = true)
    public String getSymbol() {
        return this.symbol;
    }
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

}
