/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : DacJournal.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.api.io.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DacJournal generated by hbm2java
*/
@Entity
@Table(
    name="dac_journal")
@ApiModel
public class DacJournal  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private int journalid;
     private Integer progress;
     private String status;
     private String processstep;
     private String arguments;
     private Date startts;
     private Date endts;
     private Date lastupdate;
     private String user;
     private Set<DacMessages> dacMessageses = new HashSet<DacMessages>(0);

    public DacJournal() {
    }

	
    public DacJournal(int journalid) {
        this.journalid = journalid;
    }
    public DacJournal(int journalid, Integer progress, String status, String processstep, String arguments, Date startts, Date endts, Date lastupdate, String user, Set<DacMessages> dacMessageses) {
       this.journalid = journalid;
       this.progress = progress;
       this.status = status;
       this.processstep = processstep;
       this.arguments = arguments;
       this.startts = startts;
       this.endts = endts;
       this.lastupdate = lastupdate;
       this.user = user;
       this.dacMessageses = dacMessageses;
    }

    @Id     
    @Column(name="journalid", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public int getJournalid() {
        return this.journalid;
    }
    
    public void setJournalid(int journalid) {
        this.journalid = journalid;
    }
    
    @Column(name="progress")
    @ApiModelProperty(required = true)
    public Integer getProgress() {
        return this.progress;
    }
    
    public void setProgress(Integer progress) {
        this.progress = progress;
    }
    
    @Column(name="status", length=100)
    @ApiModelProperty(required = true)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="processstep", length=100)
    @ApiModelProperty(required = true)
    public String getProcessstep() {
        return this.processstep;
    }
    
    public void setProcessstep(String processstep) {
        this.processstep = processstep;
    }
    
    @Column(name="arguments", length=100)
    @ApiModelProperty(required = true)
    public String getArguments() {
        return this.arguments;
    }
    
    public void setArguments(String arguments) {
        this.arguments = arguments;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="startts", length=13)
    @ApiModelProperty(required = true)
    public Date getStartts() {
        return this.startts;
    }
    
    public void setStartts(Date startts) {
        this.startts = startts;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="endts", length=13)
    @ApiModelProperty(required = true)
    public Date getEndts() {
        return this.endts;
    }
    
    public void setEndts(Date endts) {
        this.endts = endts;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="lastupdate", length=13)
    @ApiModelProperty(required = true)
    public Date getLastupdate() {
        return this.lastupdate;
    }
    
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }
    
    @Column(name="user", length=100)
    @ApiModelProperty(required = true)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    @OneToMany(fetch=FetchType.LAZY, mappedBy="dacJournal")
    @ApiModelProperty(required = true)
    public Set<DacMessages> getDacMessageses() {
        return this.dacMessageses;
    }
    
    public void setDacMessageses(Set<DacMessages> dacMessageses) {
        this.dacMessageses = dacMessageses;
    }




}
