/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : DacMessagetype.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.api.io.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DacMessagetype generated by hbm2java
*/
@Entity
@Table(
    name="dac_messagetype")
@ApiModel
public class DacMessagetype  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private int messagetypeid;
     private String description;
     private Set<DacMessages> dacMessageses = new HashSet<DacMessages>(0);

    public DacMessagetype() {
    }

	
    public DacMessagetype(int messagetypeid) {
        this.messagetypeid = messagetypeid;
    }
    public DacMessagetype(int messagetypeid, String description, Set<DacMessages> dacMessageses) {
       this.messagetypeid = messagetypeid;
       this.description = description;
       this.dacMessageses = dacMessageses;
    }

    @Id     
    @Column(name="messagetypeid", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public int getMessagetypeid() {
        return this.messagetypeid;
    }
    
    public void setMessagetypeid(int messagetypeid) {
        this.messagetypeid = messagetypeid;
    }
    
    @Column(name="description", length=100)
    @ApiModelProperty(required = true)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @OneToMany(fetch=FetchType.LAZY, mappedBy="dacMessagetype")
    @ApiModelProperty(required = true)
    public Set<DacMessages> getDacMessageses() {
        return this.dacMessageses;
    }
    
    public void setDacMessageses(Set<DacMessages> dacMessageses) {
        this.dacMessageses = dacMessageses;
    }




}
