/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : DacMessages.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.api.io.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DacMessages generated by hbm2java
*/
@Entity
@Table(
    name="dac_messages")
@ApiModel
public class DacMessages  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private int messageid;
     private DacJournal dacJournal;
     private DacMessagetype dacMessagetype;
     private String message;
     private String severity;
     private Date auditts;
     private String user;

    public DacMessages() {
    }

	
    public DacMessages(int messageid, String message, String severity, Date auditts) {
        this.messageid = messageid;
        this.message = message;
        this.severity = severity;
        this.auditts = auditts;
    }
    public DacMessages(int messageid, DacJournal dacJournal, DacMessagetype dacMessagetype, String message, String severity, Date auditts, String user) {
       this.messageid = messageid;
       this.dacJournal = dacJournal;
       this.dacMessagetype = dacMessagetype;
       this.message = message;
       this.severity = severity;
       this.auditts = auditts;
       this.user = user;
    }

    @Id     
    @Column(name="messageid", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public int getMessageid() {
        return this.messageid;
    }
    
    public void setMessageid(int messageid) {
        this.messageid = messageid;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="journalid")
    @ApiModelProperty(required = true)
    public DacJournal getDacJournal() {
        return this.dacJournal;
    }
    
    public void setDacJournal(DacJournal dacJournal) {
        this.dacJournal = dacJournal;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="messagetypeid")
    @ApiModelProperty(required = true)
    public DacMessagetype getDacMessagetype() {
        return this.dacMessagetype;
    }
    
    public void setDacMessagetype(DacMessagetype dacMessagetype) {
        this.dacMessagetype = dacMessagetype;
    }
    
    @Column(name="message", nullable=false, length=1024)
    @ApiModelProperty(required = true)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    
    @Column(name="severity", nullable=false, length=10)
    @ApiModelProperty(required = true)
    public String getSeverity() {
        return this.severity;
    }
    
    public void setSeverity(String severity) {
        this.severity = severity;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="auditts", nullable=false, length=13)
    @ApiModelProperty(required = true)
    public Date getAuditts() {
        return this.auditts;
    }
    
    public void setAuditts(Date auditts) {
        this.auditts = auditts;
    }
    
    @Column(name="user", length=100)
    @ApiModelProperty(required = true)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }




}
