/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : DacMessages.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.api.io.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDateTime;
import java.util.Date;

import javax.persistence.*;
import javax.print.attribute.standard.Severity;

/**
 * DacMessages generated by hbm2java
*/
@Entity
@Table(
    name="dac_messages")
@ApiModel
public class DacMessages  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private int messageid;
     private DacJournal dacJournal;
     private String messagetype;
     private String message;
     private Severity severity;
     private LocalDateTime ts;
     private String user;

    public DacMessages() {
    }

	
    public DacMessages(int messageid, String message, Severity severity, LocalDateTime ts) {
        this.messageid = messageid;
        this.message = message;
        this.severity = severity;
        this.ts = ts;
    }
    public DacMessages(int messageid, DacJournal dacJournal, String messagetype, String message, Severity severity, LocalDateTime ts, String user) {
       this.messageid = messageid;
       this.dacJournal = dacJournal;
       this.messagetype = messagetype;
       this.message = message;
       this.severity = severity;
       this.ts = ts;
       this.user = user;
    }

    @Id     
    @Column(name="messageid", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public int getMessageid() {
        return this.messageid;
    }
    public void setMessageid(int messageid) {
        this.messageid = messageid;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="journalid")
    @ApiModelProperty
    public DacJournal getDacJournal() {
        return this.dacJournal;
    }
    public void setDacJournal(DacJournal dacJournal) {
        this.dacJournal = dacJournal;
    }

    @Column(name="messagetype", nullable=false, length=100)
    @ApiModelProperty(required = true)
    public String getDacMessagetype() {
        return this.messagetype;
    }
    public void setDacMessagetype(String messagetype) {
        this.messagetype = messagetype;
    }
    
    @Column(name="message", nullable=false, length=1024)
    @ApiModelProperty(required = true)
    public String getMessage() {
        return this.message;
    }
    public void setMessage(String message) {
        this.message = message;
    }

    @Enumerated
    @Column(name="severity", nullable=false)
    @ApiModelProperty(required = true)
    public Severity getSeverity() {
        return this.severity;
    }
    public void setSeverity(Severity severity) {
        this.severity = severity;
    }

    @Column(name="ts", nullable=false, length=13)
    @ApiModelProperty(required = true)
    public LocalDateTime getTs() {
        return this.ts;
    }
    public void setTs(LocalDateTime auditts) {
        this.ts = ts;
    }
    
    @Column(name="user", length=100)
    @ApiModelProperty(required = true)
    public String getUser() {
        return this.user;
    }
    public void setUser(String user) {
        this.user = user;
    }




}
