/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : DacRestauthorization.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.api.io.domain;
// Generated by Hibernate Tools 4.3.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DacRestauthorization generated by hbm2java.
 */
@Entity
@Table(name="dac_restauthorization"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"restidpattern", "restapp", "resource", "restoptype", "operations"}) 
)
@ApiModel
public class DacRestauthorization  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


    private int restauthorizationid;
    private String restapp;
    private String resource;
    private String restoptype;
    private String restidpattern;
    private String permissions;
    private String description;
    private String operations;
    private String users;



    /** Default constructor. */ 
    public DacRestauthorization() {
    }

    /** Full constructor. 
      * @param restauthorizationid Field
      * @param restapp Field
      * @param resource Field
      * @param restoptype Field
      * @param restidpattern Field
      * @param permissions Field
      * @param description Field
      * @param operations Field
      * @param users Field
    */ 
    public DacRestauthorization(int restauthorizationid, String restapp, String resource, String restoptype, String restidpattern, String permissions, String description, String operations, String users) {
        this.restauthorizationid = restauthorizationid;
        this.restapp = restapp;
        this.resource = resource;
        this.restoptype = restoptype;
        this.restidpattern = restidpattern;
        this.permissions = permissions;
        this.description = description;
        this.operations = operations;
        this.users = users;
    }
   
    @Id     
    @Column(name="restauthorizationid", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public int getRestauthorizationid() {
        return this.restauthorizationid;
    }
    
    public void setRestauthorizationid(int restauthorizationid) {
        this.restauthorizationid = restauthorizationid;
    }
    
    @Column(name="restapp", nullable=false, length=25)
    @ApiModelProperty(required = true)
    public String getRestapp() {
        return this.restapp;
    }
    
    public void setRestapp(String restapp) {
        this.restapp = restapp;
    }
    
    @Column(name="resource", nullable=false, length=25)
    @ApiModelProperty(required = true)
    public String getResource() {
        return this.resource;
    }
    
    public void setResource(String resource) {
        this.resource = resource;
    }
    
    @Column(name="restoptype", nullable=false, length=10)
    @ApiModelProperty(required = true)
    public String getRestoptype() {
        return this.restoptype;
    }
    
    public void setRestoptype(String restoptype) {
        this.restoptype = restoptype;
    }
    
    @Column(name="restidpattern", nullable=false, length=50)
    @ApiModelProperty(required = true)
    public String getRestidpattern() {
        return this.restidpattern;
    }
    
    public void setRestidpattern(String restidpattern) {
        this.restidpattern = restidpattern;
    }
    
    @Column(name="permissions", nullable=false, length=200)
    @ApiModelProperty(required = true)
    public String getPermissions() {
        return this.permissions;
    }
    
    public void setPermissions(String permissions) {
        this.permissions = permissions;
    }
    
    @Column(name="description", nullable=false, length=100)
    @ApiModelProperty(required = true)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="operations", nullable=false, length=200)
    @ApiModelProperty(required = true)
    public String getOperations() {
        return this.operations;
    }
    
    public void setOperations(String operations) {
        this.operations = operations;
    }
    
    @Column(name="users", nullable=false, length=200)
    @ApiModelProperty(required = true)
    public String getUsers() {
        return this.users;
    }
    
    public void setUsers(String users) {
        this.users = users;
    }




}


