image:
  file: .gitpod.Dockerfile

tasks:
  - init: mvn install -DskipTests=false

vscode:
  extensions:
    - sonarsource.sonarlint-vscode@1.19.0:0efl2ERJ3aA2ElF84T/Qjg==
    - vscjava.vscode-java-test@0.27.0:gNh98vNbqtZC6ydHasFxAQ==