/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : Currency.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.marketdataprovider.api.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Currency generated by hbm2java
*/
@Entity
@Table(
    name="mf_currency")
@PrimaryKeyJoinColumn(name="instrumentid")
@ApiModel
public class Currency extends Security implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private int instrumentid;
     private String currencycode;
     private Set<EndOfDayPrice> endOfDayPrices = new HashSet<EndOfDayPrice>(0);

    public Currency() {
    }

	
    public Currency(String currencycode) {
        this.currencycode = currencycode;
    }

    @Column(name="currencycode", nullable=false, length=3)
    @ApiModelProperty(required = true)
    public String getCurrencycode() {
        return this.currencycode;
    }
    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode;
    }


    @OneToMany(fetch=FetchType.LAZY, mappedBy="currency")
    @ApiModelProperty(required = true)
    public Set<EndOfDayPrice> getEndOfDayPrices() {
        return this.endOfDayPrices;
    }
    public void setEndOfDayPrices(Set<EndOfDayPrice> endOfDayPrices) {
        this.endOfDayPrices = endOfDayPrices;
    }




}
