/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : EndOfDayPrice.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.marketdataprovider.api.domain;
// Generated by Hibernate Tools 4.3.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.Instant;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EndOfDayPrice generated by hbm2java.
 */
@Entity
@Table(name="md_endofdayprice")
@ApiModel
public class EndOfDayPrice  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


    private Integer id;
    private Instrument instrument;
    private int currencyid;
    private LocalDate dayofprice;
    private double endofdayprice;
    private Instant lastchanged;



    /** Default constructor. */ 
    public EndOfDayPrice() {
    }

    /** Minimal constructor. 
      * @param currencyid Field
      * @param endofdayprice Field
    */ 
    public EndOfDayPrice(int currencyid, double endofdayprice) {
        this.currencyid = currencyid;
        this.endofdayprice = endofdayprice;
    }
    /** Full constructor. 
      * @param instrument Field
      * @param currencyid Field
      * @param dayofprice Field
      * @param endofdayprice Field
      * @param lastchanged Field
    */ 
    public EndOfDayPrice(Instrument instrument, int currencyid, LocalDate dayofprice, double endofdayprice, Instant lastchanged) {
        this.instrument = instrument;
        this.currencyid = currencyid;
        this.dayofprice = dayofprice;
        this.endofdayprice = endofdayprice;
        this.lastchanged = lastchanged;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="id", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="instrument_id")
    @ApiModelProperty(required = true)
    public Instrument getInstrument() {
        return this.instrument;
    }
    
    public void setInstrument(Instrument instrument) {
        this.instrument = instrument;
    }
    
    @Column(name="currencyid", nullable=false)
    @ApiModelProperty(required = true)
    public int getCurrencyid() {
        return this.currencyid;
    }
    
    public void setCurrencyid(int currencyid) {
        this.currencyid = currencyid;
    }
    
    @Column(name="dayofprice", length=13)
    @ApiModelProperty(required = true)
    public LocalDate getDayofprice() {
        return this.dayofprice;
    }
    
    public void setDayofprice(LocalDate dayofprice) {
        this.dayofprice = dayofprice;
    }
    
    @Column(name="endofdayprice", nullable=false, precision=17, scale=17)
    @ApiModelProperty(required = true)
    public double getEndofdayprice() {
        return this.endofdayprice;
    }
    
    public void setEndofdayprice(double endofdayprice) {
        this.endofdayprice = endofdayprice;
    }
    
    @Column(name="lastchanged", length=29)
    @ApiModelProperty(required = true)
    public Instant getLastchanged() {
        return this.lastchanged;
    }
    
    public void setLastchanged(Instant lastchanged) {
        this.lastchanged = lastchanged;
    }




}


