/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : ImportType.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.marketdataprovider.api.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ImportType generated by hbm2java
*/
@Entity
@Table(
    name="mf_importtype")
@ApiModel
public class ImportType  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private int importtypeid;
     private String description;
     private Set<Source> sources = new HashSet<Source>(0);

    public ImportType() {
    }

	
    public ImportType(int importtypeid) {
        this.importtypeid = importtypeid;
    }
    public ImportType(int importtypeid, String description, Set<Source> sources) {
       this.importtypeid = importtypeid;
       this.description = description;
       this.sources = sources;
    }

    @Id     
    @Column(name="importtypeid", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public int getImporttypeid() {
        return this.importtypeid;
    }
    
    public void setImporttypeid(int importtypeid) {
        this.importtypeid = importtypeid;
    }
    
    @Column(name="description", length=100)
    @ApiModelProperty(required = true)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @OneToMany(fetch=FetchType.LAZY, mappedBy="importType")
    @ApiModelProperty(required = true)
    public Set<Source> getSources() {
        return this.sources;
    }
    
    public void setSources(Set<Source> sources) {
        this.sources = sources;
    }




}
