/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : Instrument.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.marketdataprovider.api.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.Instant;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Instrument generated by hbm2java
*/
@Entity
@Table(
    name="md_instrument")
@ApiModel
public class Instrument  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private Integer id;
     private String description;
     private int hometradingcurrencyid;
     private int instrumenttypeid;
     private String isin;
     private int sourceid;
     private String ticker;
     private Instant treelastchanged;
     private String wkn;
     private Set<EndOfDayPrice> endOfDayPrices = new HashSet<EndOfDayPrice>(0);

    public Instrument() {
    }

	
    public Instrument(int hometradingcurrencyid, int instrumenttypeid, int sourceid) {
        this.hometradingcurrencyid = hometradingcurrencyid;
        this.instrumenttypeid = instrumenttypeid;
        this.sourceid = sourceid;
    }
    public Instrument(String description, int hometradingcurrencyid, int instrumenttypeid, String isin, int sourceid, String ticker, Instant treelastchanged, String wkn, Set<EndOfDayPrice> endOfDayPrices) {
       this.description = description;
       this.hometradingcurrencyid = hometradingcurrencyid;
       this.instrumenttypeid = instrumenttypeid;
       this.isin = isin;
       this.sourceid = sourceid;
       this.ticker = ticker;
       this.treelastchanged = treelastchanged;
       this.wkn = wkn;
       this.endOfDayPrices = endOfDayPrices;
    }

    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="id", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="description")
    @ApiModelProperty(required = true)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="hometradingcurrencyid", nullable=false)
    @ApiModelProperty(required = true)
    public int getHometradingcurrencyid() {
        return this.hometradingcurrencyid;
    }
    
    public void setHometradingcurrencyid(int hometradingcurrencyid) {
        this.hometradingcurrencyid = hometradingcurrencyid;
    }
    
    @Column(name="instrumenttypeid", nullable=false)
    @ApiModelProperty(required = true)
    public int getInstrumenttypeid() {
        return this.instrumenttypeid;
    }
    
    public void setInstrumenttypeid(int instrumenttypeid) {
        this.instrumenttypeid = instrumenttypeid;
    }
    
    @Column(name="isin")
    @ApiModelProperty(required = true)
    public String getIsin() {
        return this.isin;
    }
    
    public void setIsin(String isin) {
        this.isin = isin;
    }
    
    @Column(name="sourceid", nullable=false)
    @ApiModelProperty(required = true)
    public int getSourceid() {
        return this.sourceid;
    }
    
    public void setSourceid(int sourceid) {
        this.sourceid = sourceid;
    }
    
    @Column(name="ticker")
    @ApiModelProperty(required = true)
    public String getTicker() {
        return this.ticker;
    }
    
    public void setTicker(String ticker) {
        this.ticker = ticker;
    }
    
    @Column(name="treelastchanged", length=29)
    @ApiModelProperty(required = true)
    public Instant getTreelastchanged() {
        return this.treelastchanged;
    }
    
    public void setTreelastchanged(Instant treelastchanged) {
        this.treelastchanged = treelastchanged;
    }
    
    @Column(name="wkn")
    @ApiModelProperty(required = true)
    public String getWkn() {
        return this.wkn;
    }
    
    public void setWkn(String wkn) {
        this.wkn = wkn;
    }
    @OneToMany(fetch=FetchType.LAZY, mappedBy="instrument")
    @ApiModelProperty(required = true)
    public Set<EndOfDayPrice> getEndOfDayPrices() {
        return this.endOfDayPrices;
    }
    
    public void setEndOfDayPrices(Set<EndOfDayPrice> endOfDayPrices) {
        this.endOfDayPrices = endOfDayPrices;
    }




}
