/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : Instrument.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.marketdataprovider.api.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Instrument generated by hbm2java
*/
@Entity
@Table(
    name="mf_instrument")
@Inheritance(strategy= InheritanceType.JOINED)
@ApiModel
public abstract class Instrument  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private Integer instrumentid;
     private InstrumentType instrumentType;
     private Integer liquiditytypeid;
     private String description;
     private boolean isactive;
     private LocalDate maturitydate;
     private LocalDate closingdate;
     private LocalDate treelastchanged;
     private Security security;
     private Integer instrumenttypeId;

    public Instrument() {
    }

    public Instrument(Integer instrumentTypeId, String description, boolean isactive, LocalDate treelastchanged) {
        this.instrumenttypeId = instrumentTypeId;
        this.description = description;
        this.isactive = isactive;
        this.treelastchanged = treelastchanged;
    }

    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="instrumentid", unique=true, nullable=false)
    @ApiModelProperty(required = true)
    public Integer getInstrumentid() {
        return this.instrumentid;
    }
    public void setInstrumentid(Integer instrumentid) {
        this.instrumentid = instrumentid;
    }

    @Column(name = "instrumenttypeid", nullable=false)
    @ApiModelProperty(required = true)
    protected Integer getInstrumentTypeId() {
        return this.instrumenttypeId;
    }
    protected void setInstrumentTypeId(Integer instrumentTypeId) {
        this.instrumenttypeId = instrumentTypeId;
    }

    @Column(name="liquiditytypeid")
    public Integer getLiquiditytypeid() {
        return this.liquiditytypeid;
    }
    public void setLiquiditytypeid(Integer liquiditytypeid) {
        this.liquiditytypeid = liquiditytypeid;
    }
    
    @Column(name="description", nullable=false, length=100)
    @ApiModelProperty(required = true)
    public String getDescription() {
        return this.description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="isactive", nullable=false)
    @ApiModelProperty(required = true)
    public boolean isIsactive() {
        return this.isactive;
    }
    public void setIsactive(boolean isactive) {
        this.isactive = isactive;
    }
    
    @Column(name="maturitydate", length=13)
    public LocalDate getMaturitydate() {
        return this.maturitydate;
    }
    public void setMaturitydate(LocalDate maturitydate) {
        this.maturitydate = maturitydate;
    }
    
    @Column(name="closingdate", length=13)
    public LocalDate getClosingdate() {
        return this.closingdate;
    }
    public void setClosingdate(LocalDate closingdate) {
        this.closingdate = closingdate;
    }
    
    @Column(name="treelastchanged", nullable=false, length=13)
    @ApiModelProperty(required = true)
    public LocalDate getTreelastchanged() {
        return this.treelastchanged;
    }
    public void setTreelastchanged(LocalDate treelastchanged) {
        this.treelastchanged = treelastchanged;
    }

}
