/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : Security.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.dac.marketdataprovider.api.domain;
// Generated by Hibernate Tools 5.2.5.Final


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Security generated by hbm2java
*/
@Entity
@Table(
    name="mf_security")
@PrimaryKeyJoinColumn(name="instrumentid")
@Inheritance(strategy= InheritanceType.JOINED)
@ApiModel
public class Security extends Instrument implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private String isin;
    private String wkn;
    private String ticker;
    private Set<EndOfDayPrice> endOfDayPrices = new HashSet<EndOfDayPrice>(0);
    private Set<SecuritySymbols> securitySymbols = new HashSet<SecuritySymbols>(0);
    private Integer securityTypeId;

    public Security() {
    }

    public Security(String description,
            boolean isactive,
            LocalDate treelastchanged,
            SecurityType securityType,
            String isin) {
        super(InstrumentType.SECURITY.getValue(), description, isactive, treelastchanged);

        this.securityTypeId = securityType.getValue();
        this.isin = isin;
    }

    @Column(name = "securitytypeid", nullable=false)
    @ApiModelProperty(required = true)
    protected Integer getSecurityTypeId() {
        return this.securityTypeId;
    }
    protected void setSecurityTypeId(Integer securityTypeId) {
        this.securityTypeId = securityTypeId;
    }

    @Transient
    public SecurityType getSecurityType(){
        if(getSecurityTypeId()==1) return SecurityType.EQUITY;
        if(getSecurityTypeId()==2) return SecurityType.CURRENCY;
        return SecurityType.UNKNOWN;
    }


    
    @Column(name="isin", length=12)
    @ApiModelProperty(required = true)
    public String getIsin() {
        return this.isin;
    }
    public void setIsin(String isin) {
        this.isin = isin;
    }
    
    @Column(name="wkn", length=10)
    public String getWkn() {
        return this.wkn;
    }
    public void setWkn(String wkn) {
        this.wkn = wkn;
    }
    
    @Column(name="ticker", length=20)
    public String getTicker() {
        return this.ticker;
    }
    public void setTicker(String ticker) {
        this.ticker = ticker;
    }


    @OneToMany(fetch=FetchType.LAZY, mappedBy="security")
    @ApiModelProperty(required = true)
    public Set<EndOfDayPrice> getEndOfDayPrices() {
        return this.endOfDayPrices;
    }
    public void setEndOfDayPrices(Set<EndOfDayPrice> endOfDayPrices) {
        this.endOfDayPrices = endOfDayPrices;
    }

    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name = "instrumentid")
    @ApiModelProperty(required = true)
    public Set<SecuritySymbols> getSecuritySymbols() {
        return this.securitySymbols;
    }
    public void setSecuritySymbols(Set<SecuritySymbols> securitySymbols) {
        this.securitySymbols = securitySymbols;
    }


}
