#my fist playbook
-
 name: Play 1
 hosts: CentOSServer
 remote_user: holger
 become: true
 become_method: sudo
 vars:
  download_folder: /mnt/data/software/
  java_pkg: "{{download_folder}}java/jdk-8u181-linux-x64.rpm"
  maven_version: "apache-maven-3.5.4"
  maven_tar: "{{download_folder}}maven/{{maven_version}}-bin.tar.gz"
  username: "builder"
 tasks:
# - name: upgrade all packages
#   yum:
#    name: '*'
#    state: latest
#    exclude: kernel*
 - name: install nfs server
   action: yum pkg=nfs-utils state=present
   tags:
    - nfs
 - name: create dir for mnt
   file: path=/mnt/data state=directory
   tags:
    - nfs
 - name: mount fileshare
   mount: path="/mnt/data" src="192.168.100.6://volume1/nfsshare" opts="rw" fstype="nfs" state="mounted"
   tags:
    - nfs
# - name: set permission for mnt/data
#   file: dest=/mnt/data mode=0755 recurse=yes
#   tags:
#    - nfs
 - name: install java
   action: yum pkg={{java_pkg}} state=present
   tags:
    - java
 - name: create dir for maven
   file: path=/opt/maven state=directory
   tags:
    - maven
 - name: Untar Maven
   unarchive: src="{{maven_tar}}" dest=/opt/maven remote_src="yes"
   tags:
    - maven
 - name: setup link to maven current
   file: path="/opt/maven/current" src="/opt/maven/{{maven_version}}"
          state=link
          force=yes
   tags:
    - maven
#not working ich muss hier einen neuen user anlegen und das profil anpassen
# - name: Update path for maven use
#   shell: export PATH=/opt/maven/current/bin:$PATH
#   tags:
#    - maven
 - name: install git
   action: yum pkg=git state=present
   tags:
    - git
 - name: install docker prequisits
   action: yum pkg=yum-utils,device-mapper-persistent-data,lvm2 state=present
   tags:
    - docker
 - name: install yum repo for docker
   get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
   tags:
    - docker
 - name: install docker
   action: yum pkg=docker-ce state=present
   tags:
    - docker
 - lineinfile:
    path: '/lib/systemd/system/docker.service'
    regexp: '^ExecStart=/usr/bin/dockerd'
    line: 'ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375'
 - name: create directory docker.service.d
   file: path='/etc/systemd/system/docker.service.d' state=directory
 - name: create file /etc/systemd/system/docker.service.d/docker.conf
   file: path='/etc/systemd/system/docker.service.d/docker.conf' state=touch
 - copy:
    dest: '/etc/systemd/system/docker.service.d/docker.conf'
    content: |
     [Service]
     ExecStart=
     ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix://var/run/docker.sock
 - name: Ensure docker deamon is restarted
   service:
    name: docker
    state: restarted
 - name: init swarm
   shell: docker swarm init
# net-tools ist ein paket von netzwerktools wie ifconfig. die meisten sind obsolet ifconfig z.b. durch ip addr. -> wirklich für open shift benötigt?
 - name: install net-tools
   action: yum pkg=net-tools state=present
   tags:
    - nettools
 - name: install wget
   action: yum pkg=wget state=present
   tags:
    - wget
 - name: install some tools
   action: yum pkg=bind-utils,iptables-services,bridge-utils,bash-completion,kexec-tools,sos,psacct,openssl-devel,httpd-tools,NetworkManager,python-cryptography,python-devel,python-
passlib state=present
 - name: Add the user
   user:
    name: '{{username}}'
    comment: the user builder
    uid: 1001
    #die wheel group ist bei centos automatisch mit sudo rechten in /etc/sudoers ausgestattet
    groups: wheel,docker
    #eine SHA512 verschlüsselung funktioniert nicht mit CentOS keine ahnung warum(wegen Salt-zufallswort von system davor gesetzt-pw muss auf dem rechner generiert werden). Das pw i
st aus etc/shadow von dem user holger kopiert
    password: '$6$735ANilOhfFE6moc$y7YmYDoYnxKC3UrX2eNicy7NRIvNdweqhCvT3YAPAHaoxqXu4fJJClh../0Wi1hYuvMUmFXzZfpszGHGhyDuC1'
 - lineinfile:
    path: '/home/{{username}}/.bash_profile'
    state: present
    line: 'export JAVA_HOME=/usr/java/latest'
 - lineinfile:
    path: '/home/{{username}}/.bash_profile'
    state: present
    line: 'export M2_HOME=/opt/maven/current'
 - lineinfile:
    path: '/home/{{username}}/.bash_profile'
    state: present
    line: 'export PATH=$PATH:$JAVA_HOME/bin:$M2_HOME/bin'
 - git:
    repo: 'https://holgerfischer:Jopaul09!@bitbucket.org/holgerfischer/dac.git'
    dest: '/home/{{username}}/repo/dac'
    umask: '0'
