#my fist playbook
-
 name: Play 1
 hosts: CentOSServer
 remote_user: holger
 become: true
 become_method: sudo
 vars:
  download_folder: /mnt/data/software/
  java_pkg: "{{download_folder}}java/jdk-8u181-linux-x64.rpm"
  maven_version: "apache-maven-3.5.4"
  maven_tar: "{{download_folder}}maven/{{maven_version}}-bin.tar.gz"
  username: "builder"
  clientip: "192.168.100.71"
  git_version: 2.19.0
  git_url: "https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz"
 tasks:
# - name: upgrade all packages
#   yum:
#    name: '*'
#    state: latest
#    exclude: kernel*
 - name: install nfs server
   action: yum pkg=nfs-utils state=present
   tags:
    - nfs
 - name: create dir for mnt
   file: path=/mnt/data state=directory
   tags:
    - nfs    
 - name: mount fileshare
   mount: path="/mnt/data" src="192.168.100.6://volume1/nfsshare" opts="rw" fstype="nfs" state="mounted"
   tags:
    - nfs
 - name: set permission for mnt/data
   file: dest=/mnt/data mode=0755 recurse=yes
   tags:
    - nfs      
 - name: install java
   action: yum pkg={{java_pkg}} state=present
   tags:
    - java
 - name: create dir for maven
   file: path=/opt/maven state=directory
   tags:
    - maven      
 - name: Untar Maven 
   unarchive: src="{{maven_tar}}" dest=/opt/maven remote_src="yes"
   tags:
    - maven
 - name: setup link to maven current
   file: path="/opt/maven/current" src="/opt/maven/{{maven_version}}" 
          state=link 
          force=yes  
   tags:
    - maven  
# - name: install git
#   action: yum pkg=git state=absent
#   tags:
#    - git
# - name: git uninstall
#   yum:
#    name: "git"
#    state: absent
 - name: Install yum package for git
   yum:
    name: "{{ item }}"
   with_items:
    - curl-devel
    - expat-devel
#    - gettext-devel
    - openssl-devel
    - zlib-devel
    - wget
    - gcc
    - cpan
 - name: Get git binary
   unarchive:
    src: "{{ git_url }}"
    dest: "/tmp"
    remote_src: yes
   changed_when: false
 - name: Make all git binary
   make:
    chdir: "/tmp/git-{{ git_version }}"
    target: all
    params:
      prefix: "/usr/local"
   changed_when: false
 - name: Make install git binary
   make:
    chdir: "/tmp/git-{{ git_version }}"
    target: install
    params:
      prefix: "/usr/local"
   changed_when: false
 - name: Remove file
   file:
    path: "/tmp/git-{{ git_version }}"
    state: absent
   changed_when: false
 - name: install docker prequisits
   action: yum pkg=yum-utils,device-mapper-persistent-data,lvm2 state=present
   tags:
    - docker
 - name: install yum repo for docker 
   get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
   tags:
    - docker
 - name: install docker
   action: yum pkg=docker-ce state=present
   tags:
    - docker
 # necessary für openshift
 - copy:
    dest: '/etc/docker/daemon.json'
    content: |
     {
      "insecure-registries" : ["172.30.0.0/16", "{{clientip}}:5000", "local.openshift:5000"]
     }
   tags:
    - docker
 - lineinfile:
    path: '/lib/systemd/system/docker.service'
    regexp: '^ExecStart=/usr/bin/dockerd'
    line: 'ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375'
 - name: create directory docker.service.d
   file: path='/etc/systemd/system/docker.service.d' state=directory
 - name: create file /etc/systemd/system/docker.service.d/docker.conf
   file: path='/etc/systemd/system/docker.service.d/docker.conf' state=touch
 - copy:
    dest: '/etc/systemd/system/docker.service.d/docker.conf'
    content: |
     [Service]
     ExecStart=
     ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix://var/run/docker.sock
 - name: Ensure docker deamon is restarted
   service:
    name: docker
    state: restarted
 - name: "get docker info"
   shell: docker info
   register: docker_info
   changed_when: false
 - name: init swarm
   shell: docker swarm init
   when: "docker_info.stdout.find('Swarm: inactive') != -1"
# net-tools ist ein paket von netzwerktools wie ifconfig. die meisten sind obsolet ifconfig z.b. durch ip addr. -> wirklich für open shift benötigt?
 - name: install net-tools
   action: yum pkg=net-tools state=present
   tags:
    - nettools 
 - name: install wget
   action: yum pkg=wget state=present
   tags:
    - wget
 - name: install some tools
   action: yum pkg=bind-utils,iptables-services,bridge-utils,bash-completion,kexec-tools,sos,psacct,openssl-devel,httpd-tools,NetworkManager,python-cryptography,python-devel,python-passlib state=present
 - name: Add the user
   user:
    name: '{{username}}'
    comment: the user builder
    uid: 1001
    #die wheel group ist bei centos automatisch mit sudo rechten in /etc/sudoers ausgestattet
    groups: wheel,docker
    #eine SHA512 verschlüsselung funktioniert nicht mit CentOS keine ahnung warum(wegen Salt-zufallswort von system davor gesetzt-pw muss auf dem rechner generiert werden). Das pw ist aus etc/shadow von dem user holger kopiert
    password: '$6$735ANilOhfFE6moc$y7YmYDoYnxKC3UrX2eNicy7NRIvNdweqhCvT3YAPAHaoxqXu4fJJClh../0Wi1hYuvMUmFXzZfpszGHGhyDuC1' 
 - lineinfile: 
    path: '/home/{{username}}/.bash_profile'
    state: present
    line: 'export JAVA_HOME=/usr/java/latest'
 - lineinfile: 
    path: '/home/{{username}}/.bash_profile'
    state: present
    line: 'export M2_HOME=/opt/maven/current'
 - lineinfile:
    path: '/home/{{username}}/.bash_profile'
    state: present
    line: 'export PATH=$PATH:$JAVA_HOME/bin:$M2_HOME/bin'
 - git:
    repo: 'https://holgerfischer:Jopaul09!@bitbucket.org/holgerfischer/dac.git'
    dest: '/home/{{username}}/repo/dac'
    umask: '0'
 - name: download openshift
   get_url:
    url: https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
    dest: /tmp
   tags:
    - oc
 - name: Untar open shift 
   unarchive: src="/tmp/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz" dest=/tmp/ remote_src="yes"
   tags:
    - oc
 - name: copy open shift to user bin
   copy:
    src: /tmp/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit/oc
    dest: /usr/bin/
    remote_src: yes
    mode: 0755
   tags:
    - oc
 - lineinfile:
    path: '/etc/hosts'
    state:  present
    line: '{{clientip}}  local.openshift'
   tags: 
    - oc
 - name: start oc
   shell: oc cluster up
   tags: 
    - oc
 - name: grant user oc-admin
   shell: oc login -u system:admin && oc adm policy add-cluster-role-to-user cluster-admin {{username}}
   tags:
    - oc
 - name: copy ansible file
   copy:
    src: ./myplaybook.yml
    dest: /home/{{username}}/repo/dac/doc/install
    mode: 0755
