apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfinance
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mfbackend.mf_name }}    
  template:
    metadata:
      labels:
        app: {{ .Values.mfbackend.mf_name }}    
    spec:
      containers:
        - name: {{ .Values.mfbackend.mf_name }}      
          image: "{{ .Values.image.repository }}mfbackend:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}      
          tty: true     
          volumeMounts:
           - name: myfinanceconfig
             mountPath: /MyFinance/envconfig           
      volumes:
        - name: myfinanceconfig
          persistentVolumeClaim:
              claimName: {{ .Values.pv.configpvc }}                                            
