apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mfbackend.db_name }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mfbackend.db_name }}  
  template:
    metadata:
      labels:
        app: {{ .Values.mfbackend.db_name }}
    spec:
      containers:
        - name: {{ .Values.mfbackend.db_name }}
          image: "{{ .Values.image.repository }}mfpostgres:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}   
          volumeMounts:
           - name: myfinancedata
             mountPath: /var/lib/postgresql/data
          env:
          - name: POSTGRES_PASSWORD
            value: {{ .Values.mfbackend.db_pw }}   
      volumes:
        - name: myfinancedata
          persistentVolumeClaim:
              claimName: {{ .Values.pv.mfdbpvc }}    

---

apiVersion: batch/v1
kind: Job
metadata:
  name: mfupgrade
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "3"  
spec:
  #autocleanup after seconds
  ttlSecondsAfterFinished: 180
  template:
    spec:
      containers: 
      - name: mfupgrade
        image: "{{ .Values.image.repository }}mfdbupdate:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}                     
        env:
        - name: DB_PW
          value: "{{ .Values.mfbackend.db_pw }}"   
        - name: DB_IMAGE
          value: {{ .Values.mfbackend.db_name }}  
        - name: DB_USER
          value: postgres  
      restartPolicy: OnFailure     
  backoffLimit: 4  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfinance
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mfbackend.mf_name }}    
  template:
    metadata:
      labels:
        app: {{ .Values.mfbackend.mf_name }}    
    spec:
      containers:
        - name: {{ .Values.mfbackend.mf_name }}      
          image: "{{ .Values.image.repository }}mfbackend:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}      
          tty: true     
          volumeMounts:
           - name: myfinanceconfig
             mountPath: /MyFinance/envconfig           
      volumes:
        - name: myfinanceconfig
          persistentVolumeClaim:
              claimName: {{ .Values.pv.configpvc }}                         
