---
  - name: manual install of containerd
    dnf:
     enablerepo: 'https://download.docker.com/linux/centos/docker-ce.repo'
     name: 'https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm'
     state: present
    tags:
     - docker 
  - name: install dnf docker
    dnf:
     enablerepo: 'https://download.docker.com/linux/centos/docker-ce.repo'
     name: docker-ce
     state: present
    tags:
     - docker      
  - name: enable docker service
    shell: systemctl enable --now docker
    tags:
     - docker     
  - name: disable firewalld DNS resolution work inside Docker containers, we must disable firewalld (a system reboot may be also needed)
    shell: systemctl disable firewalld
    tags:
     - docker      

