version: '3.4'
services:
  postgres_mf:
    image: holgerfischer/myfinance:${project.version}-mfdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    environment:
      POSTGRES_PASSWORD: vulkan
    volumes:
      - "imyfinancedata:/var/lib/postgresql/data"
    networks:
      - imyfinance-network
  mf_db_model_upgrade:
    image: holgerfischer/myfinance:${project.version}-mfdbupgrade
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    environment:
      DB_PW: vulkan
      DB_IMAGE: postgres_mf
      DB_USER: postgres
    networks:
      - imyfinance-network
    depends_on:
      - postgres_mf
  myfinance:
    image: holgerfischer/myfinance:${project.version}-myfinance
    tty: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    environment:
      DB_PW: vulkan
      DB_IMAGE: postgres_mf
      DB_USER: postgres
    ports:
      - '8181:8181'
    networks:
      - imyfinance-network
    depends_on:
      - mf_db_model_upgrade
networks:
  imyfinance-network:
volumes:
  imyfinancedata:
