

#
# Elastic Search configuration
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-logging
  #namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch-logging
  labels:
    k8s-app: elasticsearch-logging
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  #namespace: kube-system
  name: elasticsearch-logging
  labels:
    k8s-app: elasticsearch-logging
subjects:
- kind: ServiceAccount
  name: elasticsearch-logging
  #namespace: kube-system
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: elasticsearch-logging
  apiGroup: ""

---

# Elasticsearch deployment itself
apiVersion: apps/v1
kind: StatefulSet
#kind: Deployment
metadata:
  name: elasticsearch-logging
  #namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    version: v7.4.2
spec:
  serviceName: elasticsearch-logging
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch-logging
      version: v7.4.2
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v7.4.2
    spec:
      serviceAccountName: elasticsearch-logging
      containers:
      - image: quay.io/fluentd_elasticsearch/elasticsearch:v7.4.2
        name: elasticsearch-logging
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-logging
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: elasticsearch-logging
        persistentVolumeClaim:
          claimName: elasticpvc    
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-logging-init
        securityContext:
          privileged: true        

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  #namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: 9200
  type: ClusterIP 
  selector:
    k8s-app: elasticsearch-logging

---    


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticpvc
  #namespace: kube-system
spec:
  storageClassName: elasticstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: localselasticstorage
  #namespace: kube-system
spec:
  storageClassName: elasticstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /opt/elastic/
    type: DirectoryOrCreate   