apiVersion: v1
kind: Service
metadata:
 name: fleetman-webapp
spec:
 #this defines which pod is going to be presented by this service
 selector:
  app: webapp
 ports:
  - name: http
    port: 80
    nodePort: 30080
 type: NodePort
 
---

apiVersion: v1
kind: Service
metadata:
 name: fleetman-queue
spec:
 #this defines which pod is going to be presented by this service
 selector:
  app: queue
 ports:
  - name: http
    port: 8161
    nodePort: 30010
 type: NodePort
 
---

apiVersion: v1
kind: Service
metadata:
 name: mfdb
spec:
 #this defines which pod is going to be presented by this service
 selector:
  app: mfdb
 ports:
  - name: mfdb
    port: 5432
 type: ClusterIP  
 
---

apiVersion: v1
kind: Service
metadata:
 name: adminer
spec:
 #this defines which pod is going to be presented by this service
 selector:
  app: adminer
 ports:
  - name: adminer
    port: 8080
    nodePort: 30088
 type: NodePort 
 
---

apiVersion: v1
kind: Service
metadata:
 name: myfinance
spec:
 #this defines which pod is going to be presented by this service
 selector:
  app: myfinance
 ports:
  - name: myfinance
    port: 8181
    nodePort: 30081
 type: NodePort 
