apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfdb  
  template:
    metadata:
      labels:
        app: mfdb
    spec:
      containers:
        - name: mfdb
          image: holgerfischer/myfinance:0.13.0-SNAPSHOT-mfdb
          volumeMounts:
           - name: myfinancedata
             mountPath: /var/lib/postgresql/data
          env:
          - name: POSTGRES_PASSWORD
            value: vulkan
      volumes:
        - name: myfinancedata
          persistentVolumeClaim:
              claimName: mfdbpvc            

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer  
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer   
          
---

apiVersion: batch/v1
kind: Job
metadata:
  name: mfupgrade
spec:
  template:
    spec:
      containers: 
      - name: mfupgrade
        image: holgerfischer/myfinance:0.13.0-SNAPSHOT-mfdbupgrade                
        env:
        - name: DB_PW
          value: "vulkan"   
        - name: DB_IMAGE
          value: mfdb  
        - name: DB_USER
          value: postgres  
      restartPolicy: OnFailure     
  backoffLimit: 4

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mycron
spec:
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of week (0 - 6) (Sunday to Saturday;
# │ │ │ │ │                                       7 is also Sunday on some systems)
# │ │ │ │ │
# │ │ │ │ │
# * * * * *  command to execute
  schedule: "1 22 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers: 
          - name: dump
            image: holgerfischer/myfinance:0.13.0-SNAPSHOT-mfdump                
            env:
            - name: PGPASSWORD
              value: "vulkan"     
            volumeMounts:
            - name: myfinancedumps
              mountPath: /var/dumps
          volumes:
          - name: myfinancedumps
            persistentVolumeClaim:
              claimName: mfdumppvc 
          restartPolicy: OnFailure     
      backoffLimit: 4        
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfinance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfinance  
  template:
    metadata:
      labels:
        app: myfinance
    spec:
      containers:
        - name: myfinance  
          image: holgerfischer/myfinance:0.13.0-SNAPSHOT-myfinance-full      
          tty: true     
          volumeMounts:
           - name: myfinanceconfig
             mountPath: /MyFinance/envconfig           
      volumes:
        - name: myfinanceconfig
          persistentVolumeClaim:
              claimName: mfconfigpvc                 
            
            
   
          