/**
 * Dac Services
 * Dac Service REST API
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package de.hf.dac.marketdata.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HelloApi
 */
public class HelloApiTest {

    private final HelloApi api = new HelloApi();

    
    /**
     * save Product
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addProduct_productId_descriptionTest() throws ApiException {
        String productId = null;
        String description = null;
        // String response = api.addProduct_productId_description(productId, description);

        // TODO: test validations
    }
    
    /**
     * List Environments
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEnvironmentsTest() throws ApiException {
        // List<Object> response = api.getEnvironments();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHelloTest() throws ApiException {
        // String response = api.getHello();

        // TODO: test validations
    }
    
    /**
     * get ProductObjects
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProductObjectsTest() throws ApiException {
        // List<Object> response = api.getProductObjects();

        // TODO: test validations
    }
    
    /**
     * get Products
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProductsTest() throws ApiException {
        // String response = api.getProducts();

        // TODO: test validations
    }
    
}
