/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : ${pojo.getDeclarationName()}.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 ${pojo.getPackageDeclaration()}
// Generated by Hibernate Tools ${version}

<#assign classbody>
<#include "PojoTypeDeclaration.ftl"/> {
    private static final long serialVersionUID = 1L;

 <#if !pojo.isInterface()>
  <#include "PojoFields.ftl"/>

  <#include "PojoConstructors.ftl"/>

  <#include "PojoPropertyAccessors.ftl"/>

  <#include "PojoToString.ftl"/>

  <#include "PojoEqualsHashcode.ftl"/>

 <#else>
  <#include "PojoInterfacePropertyAccessors.ftl"/>

 </#if>
 <#include "PojoExtraClassCode.ftl"/>

}
</#assign>

${pojo.generateImports()}
${classbody}