/**
 * Dac Services
 * Dac Service REST API
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package de.hf.dac.myfinance.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.LocalDate;

import java.io.Serializable;
/**
 * Instrument
 */
@javax.annotation.Generated(value = "class de.hf.dac.myfinance.codegen.MyFinanceClient_JavaGenerator", date = "2018-03-23T16:39:56.372+01:00")
public class Instrument  implements Serializable {
  @JsonProperty("instrumentid")
  private Integer instrumentid = null;

  @JsonProperty("liquiditytypeid")
  private Integer liquiditytypeid = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("isactive")
  private Boolean isactive = null;

  @JsonProperty("maturitydate")
  private LocalDate maturitydate = null;

  @JsonProperty("closingdate")
  private LocalDate closingdate = null;

  @JsonProperty("treelastchanged")
  private LocalDate treelastchanged = null;

  /**
   * Gets or Sets instrumentType
   */
  public enum InstrumentTypeEnum {
    SECURITY("SECURITY"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    InstrumentTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InstrumentTypeEnum fromValue(String text) {
      for (InstrumentTypeEnum b : InstrumentTypeEnum.values()) {
          if (String.valueOf(b.value).equals(text)) {
              return b;
          }
      }
      return null;
    }
  }

  @JsonProperty("instrumentType")
  private InstrumentTypeEnum instrumentType = null;

  public Instrument instrumentid(Integer instrumentid) {
    this.instrumentid = instrumentid;
    return this;
  }

   /**
   * Get instrumentid
   * @return instrumentid
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getInstrumentid() {
    return instrumentid;
  }

  public void setInstrumentid(Integer instrumentid) {
    this.instrumentid = instrumentid;
  }

  public Instrument liquiditytypeid(Integer liquiditytypeid) {
    this.liquiditytypeid = liquiditytypeid;
    return this;
  }

   /**
   * Get liquiditytypeid
   * @return liquiditytypeid
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLiquiditytypeid() {
    return liquiditytypeid;
  }

  public void setLiquiditytypeid(Integer liquiditytypeid) {
    this.liquiditytypeid = liquiditytypeid;
  }

  public Instrument description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Instrument isactive(Boolean isactive) {
    this.isactive = isactive;
    return this;
  }

   /**
   * Get isactive
   * @return isactive
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getIsactive() {
    return isactive;
  }

  public void setIsactive(Boolean isactive) {
    this.isactive = isactive;
  }

  public Instrument maturitydate(LocalDate maturitydate) {
    this.maturitydate = maturitydate;
    return this;
  }

   /**
   * Get maturitydate
   * @return maturitydate
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getMaturitydate() {
    return maturitydate;
  }

  public void setMaturitydate(LocalDate maturitydate) {
    this.maturitydate = maturitydate;
  }

  public Instrument closingdate(LocalDate closingdate) {
    this.closingdate = closingdate;
    return this;
  }

   /**
   * Get closingdate
   * @return closingdate
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getClosingdate() {
    return closingdate;
  }

  public void setClosingdate(LocalDate closingdate) {
    this.closingdate = closingdate;
  }

  public Instrument treelastchanged(LocalDate treelastchanged) {
    this.treelastchanged = treelastchanged;
    return this;
  }

   /**
   * Get treelastchanged
   * @return treelastchanged
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public LocalDate getTreelastchanged() {
    return treelastchanged;
  }

  public void setTreelastchanged(LocalDate treelastchanged) {
    this.treelastchanged = treelastchanged;
  }

  public Instrument instrumentType(InstrumentTypeEnum instrumentType) {
    this.instrumentType = instrumentType;
    return this;
  }

   /**
   * Get instrumentType
   * @return instrumentType
  **/
  @ApiModelProperty(example = "null", value = "")
  public InstrumentTypeEnum getInstrumentType() {
    return instrumentType;
  }

  public void setInstrumentType(InstrumentTypeEnum instrumentType) {
    this.instrumentType = instrumentType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Instrument instrument = (Instrument) o;
    return Objects.equals(this.instrumentid, instrument.instrumentid) &&
        Objects.equals(this.liquiditytypeid, instrument.liquiditytypeid) &&
        Objects.equals(this.description, instrument.description) &&
        Objects.equals(this.isactive, instrument.isactive) &&
        Objects.equals(this.maturitydate, instrument.maturitydate) &&
        Objects.equals(this.closingdate, instrument.closingdate) &&
        Objects.equals(this.treelastchanged, instrument.treelastchanged) &&
        Objects.equals(this.instrumentType, instrument.instrumentType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instrumentid, liquiditytypeid, description, isactive, maturitydate, closingdate, treelastchanged, instrumentType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Instrument {\n");
    
    sb.append("    instrumentid: ").append(toIndentedString(instrumentid)).append("\n");
    sb.append("    liquiditytypeid: ").append(toIndentedString(liquiditytypeid)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isactive: ").append(toIndentedString(isactive)).append("\n");
    sb.append("    maturitydate: ").append(toIndentedString(maturitydate)).append("\n");
    sb.append("    closingdate: ").append(toIndentedString(closingdate)).append("\n");
    sb.append("    treelastchanged: ").append(toIndentedString(treelastchanged)).append("\n");
    sb.append("    instrumentType: ").append(toIndentedString(instrumentType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

