/**
 * Dac Services
 * Dac Service REST API
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package de.hf.dac.myfinance.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.hf.dac.myfinance.client.model.EntityTag;
import de.hf.dac.myfinance.client.model.Link;
import de.hf.dac.myfinance.client.model.Locale;
import de.hf.dac.myfinance.client.model.MediaType;
import de.hf.dac.myfinance.client.model.NewCookie;
import de.hf.dac.myfinance.client.model.StatusType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.joda.time.DateTime;

import java.io.Serializable;
/**
 * Response
 */
@javax.annotation.Generated(value = "class de.hf.dac.myfinance.codegen.MyFinanceClient_JavaGenerator", date = "2018-04-19T16:38:35.219+02:00")
public class Response  implements Serializable {
  @JsonProperty("stringHeaders")
  private Map<String, List<String>> stringHeaders = new HashMap<String, List<String>>();

  @JsonProperty("entityTag")
  private EntityTag entityTag = null;

  @JsonProperty("links")
  private List<Link> links = new ArrayList<Link>();

  @JsonProperty("statusInfo")
  private StatusType statusInfo = null;

  @JsonProperty("mediaType")
  private MediaType mediaType = null;

  @JsonProperty("allowedMethods")
  private List<String> allowedMethods = new ArrayList<String>();

  @JsonProperty("date")
  private DateTime date = null;

  @JsonProperty("lastModified")
  private DateTime lastModified = null;

  @JsonProperty("headers")
  private Map<String, List<Object>> headers = new HashMap<String, List<Object>>();

  @JsonProperty("metadata")
  private Map<String, List<Object>> metadata = new HashMap<String, List<Object>>();

  @JsonProperty("cookies")
  private Map<String, NewCookie> cookies = new HashMap<String, NewCookie>();

  @JsonProperty("entity")
  private Object entity = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("length")
  private Integer length = null;

  @JsonProperty("language")
  private Locale language = null;

  @JsonProperty("location")
  private String location = null;

  public Response stringHeaders(Map<String, List<String>> stringHeaders) {
    this.stringHeaders = stringHeaders;
    return this;
  }

  public Response putStringHeadersItem(String key, List<String> stringHeadersItem) {
    this.stringHeaders.put(key, stringHeadersItem);
    return this;
  }

   /**
   * Get stringHeaders
   * @return stringHeaders
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, List<String>> getStringHeaders() {
    return stringHeaders;
  }

  public void setStringHeaders(Map<String, List<String>> stringHeaders) {
    this.stringHeaders = stringHeaders;
  }

  public Response entityTag(EntityTag entityTag) {
    this.entityTag = entityTag;
    return this;
  }

   /**
   * Get entityTag
   * @return entityTag
  **/
  @ApiModelProperty(example = "null", value = "")
  public EntityTag getEntityTag() {
    return entityTag;
  }

  public void setEntityTag(EntityTag entityTag) {
    this.entityTag = entityTag;
  }

  public Response links(List<Link> links) {
    this.links = links;
    return this;
  }

  public Response addLinksItem(Link linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public Response statusInfo(StatusType statusInfo) {
    this.statusInfo = statusInfo;
    return this;
  }

   /**
   * Get statusInfo
   * @return statusInfo
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusType getStatusInfo() {
    return statusInfo;
  }

  public void setStatusInfo(StatusType statusInfo) {
    this.statusInfo = statusInfo;
  }

  public Response mediaType(MediaType mediaType) {
    this.mediaType = mediaType;
    return this;
  }

   /**
   * Get mediaType
   * @return mediaType
  **/
  @ApiModelProperty(example = "null", value = "")
  public MediaType getMediaType() {
    return mediaType;
  }

  public void setMediaType(MediaType mediaType) {
    this.mediaType = mediaType;
  }

  public Response allowedMethods(List<String> allowedMethods) {
    this.allowedMethods = allowedMethods;
    return this;
  }

  public Response addAllowedMethodsItem(String allowedMethodsItem) {
    this.allowedMethods.add(allowedMethodsItem);
    return this;
  }

   /**
   * Get allowedMethods
   * @return allowedMethods
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getAllowedMethods() {
    return allowedMethods;
  }

  public void setAllowedMethods(List<String> allowedMethods) {
    this.allowedMethods = allowedMethods;
  }

  public Response date(DateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDate() {
    return date;
  }

  public void setDate(DateTime date) {
    this.date = date;
  }

  public Response lastModified(DateTime lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Get lastModified
   * @return lastModified
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getLastModified() {
    return lastModified;
  }

  public void setLastModified(DateTime lastModified) {
    this.lastModified = lastModified;
  }

  public Response headers(Map<String, List<Object>> headers) {
    this.headers = headers;
    return this;
  }

  public Response putHeadersItem(String key, List<Object> headersItem) {
    this.headers.put(key, headersItem);
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, List<Object>> getHeaders() {
    return headers;
  }

  public void setHeaders(Map<String, List<Object>> headers) {
    this.headers = headers;
  }

  public Response metadata(Map<String, List<Object>> metadata) {
    this.metadata = metadata;
    return this;
  }

  public Response putMetadataItem(String key, List<Object> metadataItem) {
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, List<Object>> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, List<Object>> metadata) {
    this.metadata = metadata;
  }

  public Response cookies(Map<String, NewCookie> cookies) {
    this.cookies = cookies;
    return this;
  }

  public Response putCookiesItem(String key, NewCookie cookiesItem) {
    this.cookies.put(key, cookiesItem);
    return this;
  }

   /**
   * Get cookies
   * @return cookies
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, NewCookie> getCookies() {
    return cookies;
  }

  public void setCookies(Map<String, NewCookie> cookies) {
    this.cookies = cookies;
  }

  public Response entity(Object entity) {
    this.entity = entity;
    return this;
  }

   /**
   * Get entity
   * @return entity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Object getEntity() {
    return entity;
  }

  public void setEntity(Object entity) {
    this.entity = entity;
  }

  public Response status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Response length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public Response language(Locale language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(example = "null", value = "")
  public Locale getLanguage() {
    return language;
  }

  public void setLanguage(Locale language) {
    this.language = language;
  }

  public Response location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Response response = (Response) o;
    return Objects.equals(this.stringHeaders, response.stringHeaders) &&
        Objects.equals(this.entityTag, response.entityTag) &&
        Objects.equals(this.links, response.links) &&
        Objects.equals(this.statusInfo, response.statusInfo) &&
        Objects.equals(this.mediaType, response.mediaType) &&
        Objects.equals(this.allowedMethods, response.allowedMethods) &&
        Objects.equals(this.date, response.date) &&
        Objects.equals(this.lastModified, response.lastModified) &&
        Objects.equals(this.headers, response.headers) &&
        Objects.equals(this.metadata, response.metadata) &&
        Objects.equals(this.cookies, response.cookies) &&
        Objects.equals(this.entity, response.entity) &&
        Objects.equals(this.status, response.status) &&
        Objects.equals(this.length, response.length) &&
        Objects.equals(this.language, response.language) &&
        Objects.equals(this.location, response.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stringHeaders, entityTag, links, statusInfo, mediaType, allowedMethods, date, lastModified, headers, metadata, cookies, entity, status, length, language, location);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Response {\n");
    
    sb.append("    stringHeaders: ").append(toIndentedString(stringHeaders)).append("\n");
    sb.append("    entityTag: ").append(toIndentedString(entityTag)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    statusInfo: ").append(toIndentedString(statusInfo)).append("\n");
    sb.append("    mediaType: ").append(toIndentedString(mediaType)).append("\n");
    sb.append("    allowedMethods: ").append(toIndentedString(allowedMethods)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    cookies: ").append(toIndentedString(cookies)).append("\n");
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

