/**
 * Dac Services
 * Dac Service REST API
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package de.hf.dac.marketdata.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
/**
 * Instrument
 */
@javax.annotation.Generated(value = "class de.hf.dac.marketdata.codegen.MarketDataClient_JavaGenerator", date = "2017-05-10T17:16:12.411+02:00")
public class Instrument  implements Serializable {
  @JsonProperty("instrumentTypeId")
  private Integer instrumentTypeId = null;

  @JsonProperty("sourceId")
  private Integer sourceId = null;

  @JsonProperty("isin")
  private String isin = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("wkn")
  private String wkn = null;

  @JsonProperty("ticker")
  private String ticker = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("treeLastChanged")
  private Long treeLastChanged = null;

  @JsonProperty("homeTradingCurrencyId")
  private Integer homeTradingCurrencyId = null;

  public Instrument instrumentTypeId(Integer instrumentTypeId) {
    this.instrumentTypeId = instrumentTypeId;
    return this;
  }

   /**
   * Get instrumentTypeId
   * @return instrumentTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getInstrumentTypeId() {
    return instrumentTypeId;
  }

  public void setInstrumentTypeId(Integer instrumentTypeId) {
    this.instrumentTypeId = instrumentTypeId;
  }

  public Instrument sourceId(Integer sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * Get sourceId
   * @return sourceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSourceId() {
    return sourceId;
  }

  public void setSourceId(Integer sourceId) {
    this.sourceId = sourceId;
  }

  public Instrument isin(String isin) {
    this.isin = isin;
    return this;
  }

   /**
   * Get isin
   * @return isin
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIsin() {
    return isin;
  }

  public void setIsin(String isin) {
    this.isin = isin;
  }

  public Instrument id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Instrument wkn(String wkn) {
    this.wkn = wkn;
    return this;
  }

   /**
   * Get wkn
   * @return wkn
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWkn() {
    return wkn;
  }

  public void setWkn(String wkn) {
    this.wkn = wkn;
  }

  public Instrument ticker(String ticker) {
    this.ticker = ticker;
    return this;
  }

   /**
   * Get ticker
   * @return ticker
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTicker() {
    return ticker;
  }

  public void setTicker(String ticker) {
    this.ticker = ticker;
  }

  public Instrument description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Instrument treeLastChanged(Long treeLastChanged) {
    this.treeLastChanged = treeLastChanged;
    return this;
  }

   /**
   * Get treeLastChanged
   * @return treeLastChanged
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTreeLastChanged() {
    return treeLastChanged;
  }

  public void setTreeLastChanged(Long treeLastChanged) {
    this.treeLastChanged = treeLastChanged;
  }

  public Instrument homeTradingCurrencyId(Integer homeTradingCurrencyId) {
    this.homeTradingCurrencyId = homeTradingCurrencyId;
    return this;
  }

   /**
   * Get homeTradingCurrencyId
   * @return homeTradingCurrencyId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getHomeTradingCurrencyId() {
    return homeTradingCurrencyId;
  }

  public void setHomeTradingCurrencyId(Integer homeTradingCurrencyId) {
    this.homeTradingCurrencyId = homeTradingCurrencyId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Instrument instrument = (Instrument) o;
    return Objects.equals(this.instrumentTypeId, instrument.instrumentTypeId) &&
        Objects.equals(this.sourceId, instrument.sourceId) &&
        Objects.equals(this.isin, instrument.isin) &&
        Objects.equals(this.id, instrument.id) &&
        Objects.equals(this.wkn, instrument.wkn) &&
        Objects.equals(this.ticker, instrument.ticker) &&
        Objects.equals(this.description, instrument.description) &&
        Objects.equals(this.treeLastChanged, instrument.treeLastChanged) &&
        Objects.equals(this.homeTradingCurrencyId, instrument.homeTradingCurrencyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instrumentTypeId, sourceId, isin, id, wkn, ticker, description, treeLastChanged, homeTradingCurrencyId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Instrument {\n");
    
    sb.append("    instrumentTypeId: ").append(toIndentedString(instrumentTypeId)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    wkn: ").append(toIndentedString(wkn)).append("\n");
    sb.append("    ticker: ").append(toIndentedString(ticker)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    treeLastChanged: ").append(toIndentedString(treeLastChanged)).append("\n");
    sb.append("    homeTradingCurrencyId: ").append(toIndentedString(homeTradingCurrencyId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

