---
  - name: Add the user
    user:
     name: '{{username}}'
     comment: the user builder
     uid: 1001
     #die wheel group ist bei centos automatisch mit sudo rechten in /etc/sudoers ausgestattet
     groups: wheel,docker
     password: '{{password}}'
  - lineinfile:
     path: '/home/{{username}}/.bash_profile'
     state: present
     line: 'export JAVA_HOME=/usr/java/latest'
  - lineinfile:
     path: '/home/{{username}}/.bash_profile'
     state: present
     line: 'export M2_HOME=/opt/maven/current'
  - lineinfile:
     path: '/home/{{username}}/.bash_profile'
     state: present
     line: 'export PATH=$PATH:$JAVA_HOME/bin:$M2_HOME/bin'
  - git:
     repo: '{{repourl}}'
     dest: '/home/{{username}}/repo/dac'
     umask: '0'
